### ISSUE TITLE
Pymongo has moved the 'binary' module to 'bson'

### ISSUE THREAD

**Issue by derekmcold** [Fiedzia/Fang-of-Mongo#11]
Get an error:

AttributeError module object has no attribute 'binary'

Caused by the latest pymongo 1.9 moving the 'binary' module from pymongo to bson.

**Comment by derekmcold** [comment]
Forked and fixed: 

git://github.com/derek/Fang-of-Mongo.git

**Comment by davidmiller** [comment]
Still an issue for me - 
this commit fixes it though :
http://github.com/derek/Fang-of-Mongo/commit/a5de189acca4de700533e7396e78bc336abba5cb

**Comment by ashokrkm** [comment]
thanks for the fork and fix, works great now.

**Comment by drubin** [comment]
Thanks derek this fixes it for me as well.. Maybe the owner of the project could actually accept this patch? 

Have you submitted a pull request?

**Comment by 4ybaka** [comment]
Still not works for me in both repos.

**Comment by JeffAMcGee** [comment]
The patch did not work for me, so I wrote another one. The code is attached to the pull request in issue #14.

My fork with just that one patch is here:
https://github.com/JeffAMcGee/Fang-of-Mongo/tree/fix-binary

**Comment by martinhbramwell** [comment]
Jeff,

I tried your patch but get the following.  I know nothing about Python so I'm afraid I don't know where to begin to try to solve the problem myself.  Sorry.

LucyLynxVps:~/programs/org/fangOfMongo/Fang-of-Mongo/fangofmongo$ python ./manage.py runserver
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    execute_manager(settings)
  File "/usr/lib/pymodules/python2.6/django/core/management/**init**.py", line 362, in execute_manager
    utility.execute()
  File "/usr/lib/pymodules/python2.6/django/core/management/**init**.py", line 303, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/pymodules/python2.6/django/core/management/**init**.py", line 252, in fetch_command
    app_name = get_commands()[subcommand]
  File "/usr/lib/pymodules/python2.6/django/core/management/**init**.py", line 101, in get_commands
    apps = settings.INSTALLED_APPS
  File "/usr/lib/pymodules/python2.6/django/utils/functional.py", line 269, in **getattr**
    self._setup()
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 40, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/pymodules/python2.6/django/conf/__init__.py", line 108, in **init**
    os.environ['TZ'] = self.TIME_ZONE
  File "/usr/lib/python2.6/os.py", line 471, in **setitem**
    putenv(key, item)
TypeError: putenv() argument 2 must be string, not None
LucyLynxVps:~/programs/org/fangOfMongo/Fang-of-Mongo/fangofmongo$
